---
Resources:
  ApiCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: Delete
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_200
        HttpVersion: http2
        Comment: Kiralia Monitoring Console Distribution
        Origins:
          - Id: ApiGateway
            DomainName: !Select [2, !Split ["/", !GetAtt NuxtSsrEngineLambdaFunctionUrl.FunctionUrl]]
            OriginPath: ''
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1, TLSv1.1, TLSv1.2]
        DefaultCacheBehavior:
          TargetOriginId: ApiGateway
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          DefaultTTL: 0
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - HEAD
            - OPTIONS
            - GET
          ForwardedValues:
            QueryString: true
            Headers:
              - Accept
              - x-api-key
              - Authorization
            Cookies:
              Forward: all
        Aliases:
          - ${self:custom.urlDomain.apiDomain}
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2019
          AcmCertificateArn: ${self:custom.urlDomain.certificateArn}
Outputs:
  CloudFrontDistributionDomain:
    Value:
      Fn::GetAtt: [ CloudFrontDistribution, DomainName ]
