name: NPM audit

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    name: NPM Audit (and fix)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Audit
        uses: luisfontes19/npm-audit-action@v0.1.0
        with:
          project-path: "."
          json: false
          only: prod
          level: critical
          fix: true
          package-lock-only: false
          force: true
          git-user: action-npm-audit
          git-email: action-npm-audit
          git-message: npm fix run from npm-audit action
          git-pr-title: [SECURITY] NPM audit fix
          git-branch: npm-audit-action
          git-remote: origin
          github-token: ${{ secrets.GITHUB_TOKEN }} 